version: "3.3"

services:
  
  app:
    container_name: app_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    restart: always
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    volumes:
      - .:/app
      - /node_modules
    working_dir: /app
    networks:
      - main
    depends_on:
      - api

  api:
    container_name: app_api
    build:
      context: https://github.com/PyotrGrogorchenko/cursor-games-api.git#main:.
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000
    restart: always
    networks:
      - main
    depends_on:
      - db      
  
  db:
    container_name: app_db
    hostname: app_db
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: games
    ports:
      - 5432:5432
    volumes:
     - db-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - main

volumes:
  db-data:      
networks:
  main:
    driver: bridge   